"""
Generate a Python module with embedded endpoints.json for use in Fabric notebooks.

This allows the Source stage to bootstrap endpoints.json without requiring manual upload.
"""
import json
from pathlib import Path

def generate_endpoints_module():
    """Generate endpoints_module.py with embedded JSON."""
    repo_root = Path(__file__).parent.parent
    endpoints_json_path = repo_root / "docs" / "endpoints.json"
    
    if not endpoints_json_path.exists():
        raise FileNotFoundError(f"endpoints.json not found at {endpoints_json_path}")
    
    with open(endpoints_json_path, 'r', encoding='utf-8') as f:
        endpoints_data = json.load(f)
    
    # Generate Python module with embedded JSON (as dict for direct use)
    module_content = f'''"""
Auto-generated module containing Zephyr API endpoints metadata.

This module is generated from docs/endpoints.json and can be imported in Fabric notebooks
to bootstrap endpoints.json to the Files area when init_mode=True.

Generated by: scripts/generate_endpoints_module.py
Source: docs/endpoints.json
"""
import json

# Endpoints data as Python dict (can be used directly or serialized)
ENDPOINTS_JSON = {json.dumps(endpoints_data, indent=2)}
'''
    
    output_path = repo_root / "sourceZephyr.Notebook" / "endpoints_module.py"
    output_path.write_text(module_content, encoding='utf-8')
    print(f"✅ Generated {output_path}")
    print(f"   Contains {len(endpoints_data.get('endpoints', []))} endpoints")

if __name__ == "__main__":
    generate_endpoints_module()

